security:
    encoders:
        Renz\ModelBundle\Entity\Customer:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1
            
        Renz\ModelBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1
            
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        customer:
            entity:
                class: Renz\ModelBundle\Entity\Customer
                property: username
    
        administrator:
            entity:
                class: Renz\ModelBundle\Entity\User
                property: username

    firewalls:
        admin_area:
            provider: administrator
            pattern:   ^/admin/
            anonymous: ~
            http_basic:
            form_login:
                login_path: renz_admin_security_login
                check_path: renz_admin_security_logincheck
                csrf_provider: form.csrf_provider
            logout:
                path: renz_admin_security_logout
                target: /admin/
                invalidate_session: false #added to not get logged out if logged out in another firewall
                
        customer_area:
            provider: customer
            pattern:   ^/
            anonymous: ~
            http_basic:
            form_login:
                login_path: renz_main_security_login
                check_path: renz_main_security_logincheck
                csrf_provider: form.csrf_provider
                default_target_path: renz_main_account_index
            logout:
                path: renz_main_security_logout
                target: renz_main_security_login
                invalidate_session: false #added to not get logged out if logged out in another firewall
        
    access_control:
        - { path: ^/admin/security/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, roles: [ROLE_ADMIN, ROLE_RESERVATION] }
        
        - { path: ^/account/, roles: ROLE_USER }